### ISSUE TITLE
关于AFF模块

### ISSUE THREAD

**Issue by hellogry** [chosj95/MIMO-UNet#1]
作者您好：
我想问下AFF融合模块的三个输入的维度以及是如何reshape操作的，期待您的回复

**Comment by hellogry** [comment]
就是里面的resize操作就是用默认参数的二进制插值对吧？

**Comment by chosj95** [comment]
Hello,

Thank you for reading my paper and asking questions.
However, I hardly understand your questions due to the translation issue.
I can answer you in better quality if you could answer me in English.

**Comment by hellogry** [comment]
The resize in the AFF module is done by using nn.upsample, right? Does it use the default nearst interpolation for the parameters?

**Comment by chosj95** [comment]
Yes.
Actually, we used ```torch.nn.functional.interpolate()``` in AFF modules but ```torch.nn.functional.interpolate()``` also used nearest interpolation as a default.
Thanks.

**Comment by chosj95** [comment]
https://pytorch.org/docs/1.4.0/nn.functional.html#torch.nn.functional.interpolate

**Comment by hellogry** [comment]
Thank you for your kind reply
