### ISSUE TITLE
Checkpoint of model trained RealBlur-J dataset

### ISSUE THREAD

**Issue by pic-kk** [chosj95/MIMO-UNet#10]
Hello! Thanks for your great work!
Could you provide a checkpoint for a model trained on RealBlurJ+GOPRO dataset?

Thanks.

**Comment by chosj95** [comment]
Hi,

I uploaded a checkpoint for MIMO-UNet+ trained on the RealBlurJ+GOPRO dataset [Git Link](https://github.com/chosj95/MIMO-UNet#model).
