### ISSUE TITLE
the image shown in the paper

### ISSUE THREAD

**Issue by mmpmmpmmpjosh** [chosj95/MIMO-UNet#21]
In the Page 5 in paper (Figure 5. Several examples on the GoPro test dataset. )
I found the data in the Gopro dataset, the image is  “test/blur/GOPR0854_11_00/001653_3.png” right?
I don't see the original image as blurry as the image shown in the paper.
Were you testing the image with the original Gopro dataset?

**Comment by chosj95** [comment]
Hi,

We used the original GoPro dataset and just moved image files using preprocessing [.py file](https://github.com/chosj95/MIMO-UNet/blob/main/data/preprocessing.py).

I read your issue and checked the dataset.
However, I cannot find ```'test/blur/GOPR0854_11_00/001653_3.png'``` either in the preprocessed image following our [code](https://github.com/chosj95/MIMO-UNet/blob/main/data/preprocessing.py) or the original GoPro dataset (GOPRO_Lagre at [Link](https://seungjunnah.github.io/Datasets/gopro.html)). 
If you give me the exact file name, I can help you more.

Considering that the image file you mentioned contain 'GOPR0854_11_00', I assume your question is about the second-row image in Figure 5. right? 
I checked both the second-row image in Figure 5 and the original GoPro dataset, thoroughly. 
I think that the issued image is ```'GOPRO_Large/test/GOPR0854_11_00/blur/000010.png'``` in the original GoPro dataset (GOPRO_Lagre at [Link](https://seungjunnah.github.io/Datasets/gopro.html)), which is sufficiently blurry.
Could you check it?
