### ISSUE TITLE
about the training time

### ISSUE THREAD

**Issue by c-yn** [chosj95/MIMO-UNet#22]
Hello. Thanks for your great work and code. 
I train it using the Tesla V100 16G, and it takes about 4 hours for 50 epochs.
Could you please tell me how long it took you to train for 3000 epochs?
Thanks in advance.

**Comment by chosj95** [comment]
Hello.

Unfortunately, it took long time to train our network.
In my experience, it took about 4-5 days for MIMO-UNet.
You can easily change training schedule or hyper parameters, but it does not guarantee reported performances.

Thanks.
