### ISSUE TITLE
Realblur 데이터셋에서의 실험에 대한 질문입니다.

### ISSUE THREAD

**Issue by jhkim0759** [chosj95/MIMO-UNet#25]
안녕하십니까,

화질 개선 연구를 진행하고 있는 석사과정 학생입니다. 선배님의 훌륭한 연구에 감사 드립니다.
올려주신 MIMO-UNet 모델을 Realblur-J데이터셋에서 PSNR을 확인한 결과 28.99가 나왔습니다.
제가 성능 평가  방식에 문제가 있는지 확인 해 주실 수 있으십니까?
dataset함수는 제가 직접 구현했으며, Reablur-J 데이터셋의 Test_list 파일을 통해 데이터를 불러오는 방식으로 구현했습니다.
PSNR은 올려주신 방식과 동일하게 구했으며, 이미지 사이즈가 8의 배수가 될 수 있도록 zero padding후 forward할 수 있도록했습니다. 이후  출력 이미지를 잘라서 Ground truth와 비교하여 평가했습니다.

감사합니다.

**Comment by chosj95** [comment]
안녕하세요.

Real-Blur dataset은 Real-blur dataset 저자들이 올려준 official code를 사용해 PSNR 측정을 하였습니다.
Official code 안에는 별도의 align을 맞추는 작업이 있는것으로 보입니다.
** We measured PSNR using [official RealBlur test code](https://github.com/rimchang/RealBlur#evaluation). You can get the PSNR we achieved by cloning and following the RealBlur repository

감사합니다.

**Comment by jhkim0759** [comment]
친절한 답변 감사합니다.
