### ISSUE TITLE
Testing pretrained MIMO-UNetPlus model in GoPro dataset

### ISSUE THREAD

**Issue by XiaoBuL** [chosj95/MIMO-UNet#3]
I test GoPro test dataset which has 1111 image pairs. It presents 32.45dB. Why it is lower than 32.68 dB proposed in paper?

**Comment by chosj95** [comment]
> > The performance of the MIMO-UNet++ model, the geometric ensemble model of MIMO-UNet+, is 32.68 dB.
> > You can see this in [Performance section](https://github.com/chosj95/MIMO-UNet#Performance).
> 
> Thanks! In addition, will the MIMO-UNetPlusPlus model code be made public?

Not now, but it is scheduled.
You can see the implementation details of the geometric ensemble we used in https://github.com/chosj95/MIMO-UNet/issues/2.
