### ISSUE TITLE
RealBlur data for training

### ISSUE THREAD

**Issue by pp00704831** [chosj95/MIMO-UNet#4]
Hello,

How do you train the model for RealBlur?
Do you fine-tune on the GoPro pre-trained weights or train form  scratch with  GoPro+BSD+RealBlurR datasets like MPRNet?
And, do you plan to release the deblurring results of RealBlur_J and RealBlur_R?

**Comment by chosj95** [comment]
> Hello,
> 
> How do you train the model for RealBlur?
> Do you fine-tune on the GoPro pre-trained weights or train form scratch with GoPro+BSD+RealBlurR datasets like MPRNet?
> And, do you plan to release the deblurring results of RealBlur_J and RealBlur_R?

Hello,

We trained our network from scratch with GoPro + RealBlurR dataset. 

Unfortunately, we don't have a plan to release more results of the RealBlur, right away.

**Comment by pp00704831** [comment]
Hello,

Because you report the result of RealBlur_J in your paper,  you mean that you trained the network from scratch with GoPro + RealBlur_J ?

Second, I am curious about why the MIMO-UNet+ can obtain high results on the RealBlur_J testing set, because it does not outperform MPRNet on the GoPro testing set. 
Do you use other techniques or have some comments about it?

Thank you very much!
