### ISSUE TITLE
FLOPs?

### ISSUE THREAD

**Issue by vztu** [chosj95/MIMO-UNet#7]
Hi,

Thanks for the great work. I didn't find the FLOPs of MIMO-Unet, MIMO-Unet+ in your paper. Could you please provide such numbers?

**Comment by chosj95** [comment]
Hi,

We didn't measure the FLOPs of our models.
Instead, I attach a helpful [link](https://www.quora.com/How-do-I-compute-the-FLOPs-of-the-PyTorch-model).
